---FISD_WT_Using_ATM_and_POS
WITH USD_RATE  AS
  (
	SELECT * FROM OPENQUERY(MSTOFBEDR,
		' SELECT CASE WHEN EXC.FROMCURRENCYCODE=''MMK'' THEN ''104''
						 WHEN EXC.FROMCURRENCYCODE=''USD'' THEN ''840''
						 WHEN EXC.FROMCURRENCYCODE=''EUR'' THEN ''978''
						 WHEN EXC.FROMCURRENCYCODE=''SGD'' THEN ''702''
						 WHEN EXC.FROMCURRENCYCODE=''CNY'' THEN ''156''
						 WHEN EXC.FROMCURRENCYCODE=''JPY'' THEN ''392''
						 WHEN EXC.FROMCURRENCYCODE=''THB'' THEN ''764''
						 WHEN EXC.FROMCURRENCYCODE=''MYR'' THEN ''458''
						 WHEN EXC.FROMCURRENCYCODE=''INR'' THEN ''356''END AS C_code,
				FROMCURRENCYCODE, TOCURRENCYCODE, MULTIPLYDIVIDE, ROUND(RATE,2) AS RATE, DATELASTMODIFIED FROM WASADMIN.EXCHANGERATESHISTORY EXC
				WHERE EXC.TOCURRENCYCODE =''MMK'' AND EXC.EXCHANGERATETYPE =''SPOT'' 
				AND (EXC.FROMCURRENCYCODE,EXC.DATELASTMODIFIED) IN (SELECT FROMCURRENCYCODE, MAX(DATELASTMODIFIED)AS MAXDATE FROM WASADMIN.EXCHANGERATESHISTORY
																	WHERE TOCURRENCYCODE =''MMK'' AND EXCHANGERATETYPE =''SPOT''  
																	AND WASADMIN.UB_TODATE(DATELASTMODIFIED) <= TO_DATE(''20250520'',''YYYYMMDD'')
																	GROUP BY FROMCURRENCYCODE) --To Get Latest Exchange Rate Only
  ')
  ),

CBM_Exchange_Rate AS                 
          ( 
            

            -- SELECT DISTINCT Exc.CARDBRAND, Exc.CURRENCYCODE, Exc.CURRENCY, Exc.DATE, Exc.RATE 
                   -- FROM PSSD_Exchange_Rate Exc
                   -- WHERE Exc.DATE = (SELECT MAX(DATE) 
                   -- FROM PSSD_Exchange_Rate 
                   -- WHERE CurrencyCode = Exc.CURRENCYCODE) --To Get Latest Exchange Rate Only
			SELECT * FROM PSSD_Exchange_Rate 
						WHERE (IDFile = (SELECT MAX(IDFile) FROM PSSD_Exchange_Rate)) AND CONVERT(VARCHAR,Date,112) = '20250520'

          )




--SELECT  'FISD_WT_Using_ATM_and_POS' MISREPORTCODE,
--		'Using ATM and POS' REPORT_NAME,
--		 SOURCE AS MACHINE_NAME,
--		'' REGION,
--		'' LOCATION_TYPE,
--		 COUNT(DISTINCT(TERMINAL_ID)) as "No_of_ATM/POS",
--		 COUNT(DISTINCT(Used_Card_Quantity)) as No_of_issuing_Cards,        
--		 CURRENCY,          
--         ROUND(isnull(ABS(sum(TRANS_AMT)),0),2) as Amount, 
--         ROUND(isnull(ABS(sum(TRANS_AMT_USD)),0),2) as "Amount(Equivalent USD)", 
--         ROUND(isnull(ABS(sum(TRANS_AMT_MMK)),0),2) as "Amount(Equivalent MMK)",                 
--         CONCAT(Remarks, 'Refund Txn =', ' ', convert(char,sum(TRAN_TYPE)))  as Remarks,
--		 -- Remarks, 'Refund Txn ='   as Description, convert(char,sum(TRAN_TYPE))  as count,		  
--          '20250520' AS EDate
--           --DATEADD(DAY, -1, CONVERT(date, GETDATE())) AS EDate        
--FROM (

---------------------------------------------------------------------For Raw---------------------------------------------------------------------
Select REF_NO, CARD_NAME, CARD_NO,	
		 CASE WHEN Category_of_Card = 'DEBIT' THEN 'Debit'
			  WHEN Category_of_Card = 'CREDIT' THEN 'Credit' 
			  WHEN Category_of_Card = 'PREPAID' THEN 'Prepaid' 
			  ELSE Category_of_Card END AS "Category of Card",
CURRENCY,Used_Card_Quantity, SOURCE, USED_LOCATION,	
TRANS_COUNT, Trans_Amt,	Trans_Amt_USD,	Trans_Amt_MMK,	
MMK_Rate, Remarks, TRAN_TYPE,	
AUTHTXN_MERCHANT_ID, AUTHTXN_MERCHANT_NAME,	TERMINAL_ID, MERCHANT_TRADE_NAME, MERCHANT_DBA_NAME,	
ADDRESS,CITY, STATE, DATASOURCE FROM 

(
-----------------------------------------------------------START CardZone -------------------------------------------------------
SELECT --'20240920' AS EDate,
    AUTHTXN_RETRIEVAL_REFNO AS REF_NO,
    --CARD_NAME,
	   CASE WHEN SUBSTRING(CARD_NO,1,6) IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('9%') THEN 'MPU'
			WHEN SUBSTRING(CARD_NO,1,6) IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('6%') THEN 'MPU-UPI'
			WHEN SUBSTRING(CARD_NO,1,6) IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('3%') THEN 'MPU-JCB'
			WHEN SUBSTRING(CARD_NO,1,6) IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('4%') THEN 'Visa'
			WHEN SUBSTRING(CARD_NO,1,6) IN (SELECT BIN FROM CardIssuer) AND SUBSTRING(CARD_NO,1,6) ='519430' THEN 'MPU-Master'
			WHEN SUBSTRING(CARD_NO,1,6) IN (SELECT BIN FROM CardIssuer) AND (CARD_NO LIKE ('5%') OR CARD_NO LIKE ('2%')) AND CARD_NO !='519430'  THEN 'Master'			
			WHEN SUBSTRING(CARD_NO,1,6) NOT IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('6%') THEN 'UPI'
			WHEN SUBSTRING(CARD_NO,1,6) NOT IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('3%') THEN 'JCB'
			WHEN SUBSTRING(CARD_NO,1,6) NOT IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('4%') THEN 'Visa'
			WHEN SUBSTRING(CARD_NO,1,6) NOT IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('5%') OR CARD_NO LIKE ('2%') THEN 'Master'
     ELSE CARD_NAME  END AS CARD_NAME,CARD_NO,
	 CASE WHEN SUBSTRING(CARD_NO,1,6) IN (SELECT BIN FROM Cardissuer) THEN Cardissuer.CardType ELSE 'Credit' END AS CATEGORY_OF_CARD,
	 
	CURRENCY, AUTHTXN_CARD_NO AS Used_Card_Quantity, SOURCE, 
	'Local' as USED_LOCATION, TRANS_COUNT, 
      
		     CASE WHEN (authTXN_CURRENCY_CODE in (156,978,392 ,458,702,764) and authTXN_CURRENCY_CODE != authTXN_BILLING_CURRENCY_ID)
              THEN (AUTHTXN_REQUEST_AMT/ (select rate from USD_rate where C_code = authTXN_CURRENCY_CODE))
              WHEN (authTXN_CURRENCY_CODE not in (104,156,978,392 ,458,702,764) and  authTXN_CURRENCY_CODE != authTXN_BILLING_CURRENCY_ID AND Card_Name ='Visa')  -- For VISA 
              THEN (AUTHTXN_REQUEST_AMT/ (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'VISA'))
              WHEN (authTXN_CURRENCY_CODE not in (104,156,978,392 ,458,702,764) and  authTXN_CURRENCY_CODE != authTXN_BILLING_CURRENCY_ID AND Card_Name LIKE '%JCB')   -- For JCB
              THEN (AUTHTXN_REQUEST_AMT/ (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'JCB'))
              WHEN (AUTHTXN_CURRENCY_CODE not in (104,156,978,392 ,458,702,764) and AUTHTXN_CURRENCY_CODE != AUTHTXN_BILLING_CURRENCY_ID AND Card_Name LIKE '%Master')
              THEN (AUTHTXN_REQUEST_AMT/ (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'MASTER'))
              WHEN (authTXN_CURRENCY_CODE not in (104,156,978,392 ,458,702,764) and  authTXN_CURRENCY_CODE != authTXN_BILLING_CURRENCY_ID)
              THEN (AUTHTXN_REQUEST_AMT/ (select rate from USD_rate where C_code = 840))
              ELSE AUTHTXN_REQUEST_AMT END  AS Trans_Amt,
       
         CASE WHEN authTXN_BILLING_CURRENCY_ID != 840 AND authTXN_BILLING_CURRENCY_ID = '104'  AND Card_Name LIKE '%JCB'
              THEN (AUTHTXN_REQUEST_AMT/ (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'JCB'))
              WHEN authTXN_BILLING_CURRENCY_ID != 840 AND authTXN_BILLING_CURRENCY_ID = '104'  AND Card_Name = 'Visa'
              THEN (AUTHTXN_REQUEST_AMT/ (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'VISA'))
              WHEN authTXN_BILLING_CURRENCY_ID != 840 AND authTXN_BILLING_CURRENCY_ID = '104'  AND Card_Name LIKE '%Master'
              THEN (AUTHTXN_REQUEST_AMT/ (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'MASTER'))
              WHEN authTXN_BILLING_CURRENCY_ID != 840 AND authTXN_BILLING_CURRENCY_ID in (104,156,978,392,458,702,764) 
              THEN (AUTHTXN_REQUEST_AMT/ (select rate from USD_rate where C_code = 840))
              ELSE AUTHTXN_REQUEST_AMT END  AS  Trans_Amt_USD,
       
         CASE WHEN authTXN_CURRENCY_CODE != '104' AND authTXN_CURRENCY_CODE = authTXN_BILLING_CURRENCY_ID AND Card_Name LIKE '%JCB'
              THEN (AUTHTXN_REQUEST_AMT * (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'JCB'))
              WHEN authTXN_CURRENCY_CODE != '104' AND authTXN_CURRENCY_CODE = authTXN_BILLING_CURRENCY_ID AND Card_Name = 'Visa'
              THEN (AUTHTXN_REQUEST_AMT *(select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'VISA'))
              WHEN authTXN_CURRENCY_CODE != '104' AND authTXN_CURRENCY_CODE = authTXN_BILLING_CURRENCY_ID AND Card_Name LIKE '%Master'
              THEN (AUTHTXN_REQUEST_AMT * (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'MASTER'))
              WHEN (authTXN_BILLING_CURRENCY_ID != 104 AND authTXN_CURRENCY_CODE = authTXN_BILLING_CURRENCY_ID) 
              THEN AUTHTXN_REQUEST_AMT*(select rate from USD_rate where C_code = authTXN_CURRENCY_CODE )
              ELSE AUTHTXN_REQUEST_AMT end AS Trans_Amt_MMK, 

         CASE WHEN Card_Name = 'Visa'    THEN (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'VISA') 
              WHEN Card_Name LIKE '%JCB' THEN (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'JCB' ) 
              WHEN Card_Name LIKE '%Master'  THEN (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'MASTER')
              ELSE (select rate from USD_rate where C_code = 840 ) END AS MMK_Rate,

 		 CASE WHEN authTXN_CURRENCY_CODE in (156,978,392,458,702,764) AND Card_Name LIKE '%JCB'
              THEN '1USD' +' = '+ trim(CONVERT(CHAR, (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'JCB' ) / (select rate from USD_rate where C_code = authTXN_CURRENCY_CODE)))  +' '+ CURRENCY_CODE
              WHEN authTXN_CURRENCY_CODE in (156,978,392,458,702,764) AND Card_Name = 'Visa'  
              THEN '1USD' +' = '+ trim(CONVERT(CHAR, (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'VISA' ) / (select rate from USD_rate where C_code = authTXN_CURRENCY_CODE))) +' '+ CURRENCY_CODE
              WHEN AUTHTXN_CURRENCY_CODE in (156,978,392,458,702,764) AND Card_Name LIKE '%Master'
              THEN '1USD' +' = '+ trim(CONVERT(CHAR, (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'MASTER') / (select rate from USD_rate where C_code = AUTHTXN_CURRENCY_CODE)))+' '+ CURRENCY_CODE 
              WHEN authTXN_CURRENCY_CODE in (156,978,392,458,702,764)  
              THEN '1USD' +' = '+ trim(CONVERT(CHAR, (select rate from USD_rate where C_code = 840 ) / (select rate from USD_rate where C_code = authTXN_CURRENCY_CODE)))+CURRENCY_CODE
              ELSE ' ' END as Remarks,
		      TRAN_TYPE,

			  AUTHTXN_MERCHANT_ID,  AUTHTXN_MERCHANT_NAME, TERMINAL_ID,  MERCHANT_TRADE_NAME, MERCHANT_DBA_NAME, ADDRESS, CITY, STATE,

'EDC_Acquiring_CardZone' AS DATASOURCE

from openquery (mstocz,' 
WITH EDC_BATHCH_DATA AS (
            SELECT REQUEST_DATE AS TRN_DATE, TRANSACTION_ID,  CARD_NO, 
                 SUBSTR(REFERENCE_NUMBER,2,13) AS REFERENCE_NUMBER,
                 SUBSTR(MERCHANT_ID,2,15) AS MERCHANT_ID,
                 TERMINAL_ID, CHANNEL 
                 FROM ODI_ADW.CBM_MIS_EDC_ACQTRN
                 --WHERE REQUEST_DATE = TO_CHAR(SYSDATE-2,''YYYYMMDD'')
                 WHERE REQUEST_DATE = ''20250520''
            ) ,
ALL_CZ_DATA AS (
					SELECT DISTINCT * FROM (
						SELECT 
							AUTHTXN_RETRIEVAL_REFNO,AUTHTXN_NO,AUTHTXN_MCC_ID,AUTHTXN_TXN_ENTRY_MODE,
                            AUTHTXN_TXNTYPE_ID,AUTHTXN_SOURCE,AUTHTXN_COUNTRY_CODE,AUTHTXN_CARD_NO,
                            AUTHTXN_GEOGRAPHY_IND,AUTHTXN_CRDBRAND_ID,AUTHTXN_CRDPLAN_ID,AUTHTXN_CURRENCY_CODE,
							AUTHTXN_DEST,AUTHTXN_CUST_ID,AUTHTXN_MERC_MDR_AMT, AUTHTXN_APPROVED_AMT,AUTHTXN_REQUEST_AMT, AUTHTXN_REQUEST_DATE,
							AUTHTXN_BILLING_CURRENCY_ID,TXNTYPE_BASE_TXNTYPE_ID,BILLCURR.CURRENCY_CODE,
							CARDTYPE.INFO_DESC,CRDBRAND_TYPE,CRDPLAN_PRODUCT_NAME, 
							
							AUTHTXN_MERCHANT_ID,
							AUTHTXN_MERCHANT_NAME, 
							AUTHTXN_TERMINAL_ID, 
							MERCHANT_TRADE_NAME, MERCHANT_DBA_NAME, 
							'''' ADDRESS , '''' CITY , '''' STATE 

						FROM ONECARD.CZ_AUTHTXN 
						LEFT JOIN ONECARD.CZ_TXNTYPE ON AUTHTXN_TXNTYPE_ID = TXNTYPE_ID AND AUTHTXN_SOURCE = TXNTYPE_CHANNEL
						LEFT JOIN ONECARD.CZ_CRDBRAND ON AUTHTXN_CRDBRAND_ID = CRDBRAND_ID
						LEFT JOIN ONECARD.CZ_CRDPLAN ON AUTHTXN_CRDPLAN_ID = CRDPLAN_ID
						LEFT JOIN ONECARD.CZ_CRDCHGTYPE ON CRDPLAN_CHARGE_TYPE = CRDCHGTYPE_ID
						LEFT JOIN ONECARD.CZ_INFO CARDTYPE ON CRDCHGTYPE_CRDR_IND = CARDTYPE.INFO_CODE AND CARDTYPE.INFO_FIELD=''SETTLE_IND'' AND CARDTYPE.INFO_TABLE = ''GENERAL''
						LEFT JOIN ONECARD.CZ_CURRENCY BILLCURR ON AUTHTXN_CURRENCY_CODE = BILLCURR.CURRENCY_ID
						LEFT JOIN ONECARD.CZ_CARD CARD ON CARD.CARD_NO = AUTHTXN_CARD_NO
						LEFT JOIN ONECARD.CZ_MERCHANT ON MERCHANT_ID = AUTHTXN_MERCHANT_ID
						-- LEFT JOIN ONECARD.CZ_ADDRESS ON ADDRESS_ID = CARD.CARD_CUST_ID AND ADDRESS_TYPE_ID = ''MAIN''  --* Acquring Customer info will not keep in our DB
						WHERE --TO_CHAR(TO_DATE(AUTHTXN_REQUEST_DATE, ''yyyymmdd''),''YYYYMMDD'') = TO_CHAR(SYSDATE-1,''YYYYMMDD'')
						AUTHTXN_REQUEST_DATE =''20250520''
						AND (TXNTYPE_REV_VOID_IND IS NULL OR (TXNTYPE_REV_VOID_IND != ''R'' AND TXNTYPE_REV_VOID_IND != ''V''))
						AND AUTHTXN_TXNTYPE_ID NOT IN (''ACCTVER'',''ACCVER_QC'',''ATRFER'',''BALINQ'',''BALINQ_CA'',''BALINQ_CU'',''BALINQ_SA'',''BALINQ_UNI'',''PINCHG'',''VPREAUTH'',''RSALENOAUT'')
						AND AUTHTXN_RESPONSE_CODE=''00''
						AND AUTHTXN_MCC_ID != ''6011'' 
						AND AUTHTXN_CUST_ID IS NULL
						and AUTHTXN_SOURCE != ''MPI'' 
						
						)
					)			
 
 SELECT DISTINCT * FROM (
 SELECT AUTHTXN_RETRIEVAL_REFNO,
	   CASE WHEN M.CARD_NO LIKE (''9%'') THEN ''MPU''
            WHEN M.CARD_NO LIKE (''6%'') THEN ''UPI''
            WHEN M.CARD_NO LIKE (''3%'') THEN ''JCB''
            WHEN M.CARD_NO LIKE (''4%'') THEN ''Visa''
            WHEN M.CARD_NO LIKE (''5%'') OR M.CARD_NO LIKE (''2%'')  THEN ''Master'' --END AS CARD_NAME,
			WHEN CRDPLAN_PRODUCT_NAME LIKE ''%VISA%'' or CRDPLAN_PRODUCT_NAME LIKE ''%VSI%'' THEN ''Visa''   ---/ cardName is not cover from batch file because of this(PREAUTH & SALECOMADV) so cardName is null and use CRDPLAN_PRODUCT_NAME to fix it
			WHEN CRDPLAN_PRODUCT_NAME LIKE ''%MASTER%'' THEN ''Master''   
			WHEN CRDPLAN_PRODUCT_NAME LIKE ''%JCB%'' OR CRDPLAN_PRODUCT_NAME LIKE ''%MJC%'' THEN ''JCB''  
			WHEN CRDPLAN_PRODUCT_NAME LIKE ''%CUP%'' or CRDPLAN_PRODUCT_NAME LIKE ''%UPI%'' THEN ''UPI''  
			WHEN (CRDPLAN_PRODUCT_NAME LIKE ''%MPU%'' OR CRDPLAN_PRODUCT_NAME LIKE ''%MPS%'') 
			AND CRDPLAN_PRODUCT_NAME NOT LIKE ''%MPU/%'' THEN ''MPU'' END AS CARD_NAME,
			 
       CRDPLAN_PRODUCT_NAME,CRDBRAND_TYPE,INFO_DESC,CURRENCY_CODE,        
       CASE WHEN CURRENCY_CODE NOT IN (''MMK'',''USD'',''EUR'',''SGD'',''THB'',''CNY'',''MYR'',''JPY'') THEN ''USD''
             WHEN CURRENCY_CODE IS NULL THEN ''USD''
             ELSE CURRENCY_CODE END AS CURRENCY, 

			CASE WHEN AUTHTXN_MCC_ID= ''6011''  THEN ''ATM''
                 WHEN AUTHTXN_TXN_ENTRY_MODE IN (''CHIP_READ'',''CONTACTLESS_CHIP'',''MAGSTRIPE_READ'')  THEN ''POS''
                 WHEN AUTHTXN_TXN_ENTRY_MODE = ''MANUAL_ENTRY'' AND AUTHTXN_TXNTYPE_ID = ''SALECOMADV'' THEN ''POS''
				 WHEN AUTHTXN_SOURCE = ''EDC'' THEN ''POS''
                 WHEN AUTHTXN_TXN_ENTRY_MODE IS NULL OR  AUTHTXN_TXN_ENTRY_MODE  
                      IN ( ''ECOMMERCE'', ''ECOMMERCE_3D'', ''ECOMMERCE_ATTEMP'', ''ECOMMERCE_RECURR'', 
						   ''EGAMBLING'', ''FALL_BACK'', ''DEFAULT'', ''MANUAL_ENTRY'', ''MOTO'' , ''RECURRING'',''UNKNOWN'', ''ECOMMERCE_VBV'', 
					  	   ''ECOMMERCE_SC'',''RECURRING'',''MOTO'' ,''UNKNOWN'',''MANUAL_ENTRY'') AND AUTHTXN_TXNTYPE_ID != ''SALECOMADV'' THEN ''E-Commerce''
				WHEN AUTHTXN_SOURCE = ''MPI'' THEN ''E-Commerce'' ELSE ''None'' END AS SOURCE,	
         
           CASE WHEN (AUTHTXN_CUST_ID IS NOT NULL AND AUTHTXN_TERMINAL_ID IN (SELECT TERMINAL_ID FROM ONECARD.CZ_TERMINAL)) THEN ''ONUS'' 
                WHEN AUTHTXN_MERCHANT_ID LIKE ''AYA%'' THEN ''ONUS''---KO TINT
                ELSE AUTHTXN_MERCHANT_ID END AS TRAN_CATEGORY,				

           CASE WHEN TXNTYPE_BASE_TXNTYPE_ID IN (''PAYMENT'',''TOPUP'') THEN 0 ELSE 1 END AS TRANS_COUNT,   
		   CASE WHEN AUTHTXN_TXNTYPE_ID IN (''REFUND'',''REFUND_PRE'',''REFUND_PRV'',''REFUND1'',''REFUNDADV'',''RFNDNOAUTH'') THEN 1 ELSE 0 END AS TRAN_TYPE,
			                              

				   TO_CHAR(TO_DATE(AUTHTXN_REQUEST_DATE, ''yyyymmdd''),''YYYYMMDD'') AS TRAN_DATE,
				   --M.TRN_DATE AS TRAN_DATE,
				   AUTHTXN_MCC_ID,
				   AUTHTXN_TXN_ENTRY_MODE,
				   TXNTYPE_BASE_TXNTYPE_ID,
				   AUTHTXN_COUNTRY_CODE,
				   AUTHTXN_CARD_NO,
				   M.CARD_NO AS CARD_NO,
				   AUTHTXN_CURRENCY_CODE,
				   AUTHTXN_BILLING_CURRENCY_ID,
				   AUTHTXN_TXNTYPE_ID, AUTHTXN_APPROVED_AMT, AUTHTXN_REQUEST_AMT,     
				   AUTHTXN_MERC_MDR_AMT,
				   AUTHTXN_CUST_ID,
				   AUTHTXN_DEST,
				   AUTHTXN_SOURCE,
				   AUTHTXN_GEOGRAPHY_IND,
				  
				  AUTHTXN_MERCHANT_ID,
				  AUTHTXN_MERCHANT_NAME, 
				  AUTHTXN_TERMINAL_ID AS TERMINAL_ID, 
				  MERCHANT_TRADE_NAME, MERCHANT_DBA_NAME, 
				  ADDRESS, CITY, STATE
			FROM ALL_CZ_DATA TXN
            LEFT JOIN EDC_BATHCH_DATA M ON M.REFERENCE_NUMBER = AUTHTXN_RETRIEVAL_REFNO AND M.TRANSACTION_ID = AUTHTXN_NO
            WHERE AUTHTXN_REQUEST_DATE =''20250520'' 
			--WHERE TO_CHAR(TO_DATE(AUTHTXN_REQUEST_DATE, ''yyyymmdd''),''YYYYMMDD'') = TO_CHAR(SYSDATE-1,''YYYYMMDD'')
			) ALL_INFO WHERE SOURCE = ''POS''
')TBL LEFT JOIN CardIssuer ON CardIssuer.BIN =  SUBSTRING(CARD_NO,1,6) 
      WHERE AUTHTXN_TXNTYPE_ID NOT IN (SELECT TXNTYPE_ID FROM CZ_TRAN_TYPE) --GET CZ_TYPE UPDATE FILE FROM Ma Shwe Sin

UNION ALL

SELECT 
    AUTHTXN_RETRIEVAL_REFNO AS REF_NO,
    --CARD_NAME,
		   CASE WHEN SUBSTRING(CARD_NO,1,6) IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('9%') THEN 'MPU'
			WHEN SUBSTRING(CARD_NO,1,6) IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('6%') THEN 'MPU-UPI'
			WHEN SUBSTRING(CARD_NO,1,6) IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('3%') THEN 'MPU-JCB'
			WHEN SUBSTRING(CARD_NO,1,6) IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('4%') THEN 'Visa'
			WHEN SUBSTRING(CARD_NO,1,6) IN (SELECT BIN FROM CardIssuer) AND SUBSTRING(CARD_NO,1,6) ='519430' THEN 'MPU-Master'
			WHEN SUBSTRING(CARD_NO,1,6) IN (SELECT BIN FROM CardIssuer) AND (CARD_NO LIKE ('5%') OR CARD_NO LIKE ('2%')) AND CARD_NO !='519430'  THEN 'Master'			
			WHEN SUBSTRING(CARD_NO,1,6) NOT IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('6%') THEN 'UPI'
			WHEN SUBSTRING(CARD_NO,1,6) NOT IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('3%') THEN 'JCB'
			WHEN SUBSTRING(CARD_NO,1,6) NOT IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('4%') THEN 'Visa'
			WHEN SUBSTRING(CARD_NO,1,6) NOT IN (SELECT BIN FROM CardIssuer) AND CARD_NO LIKE ('5%') OR CARD_NO LIKE ('2%') THEN 'Master'
     ELSE CARD_NAME  END AS CARD_NAME,CARD_NO,
	 CASE WHEN SUBSTRING(CARD_NO,1,6) IN (SELECT BIN FROM Cardissuer) THEN Cardissuer.CardType ELSE 'Credit' END AS CATEGORY_OF_CARD,
	 
	CURRENCY, AUTHTXN_CARD_NO AS Used_Card_Quantity, SOURCE, 
	'Local' as USED_LOCATION, TRANS_COUNT, 
      
		     CASE WHEN (authTXN_CURRENCY_CODE in (156,978,392 ,458,702,764) and authTXN_CURRENCY_CODE != authTXN_BILLING_CURRENCY_ID)
              THEN (AUTHTXN_REQUEST_AMT/ (select rate from USD_rate where C_code = authTXN_CURRENCY_CODE))
              WHEN (authTXN_CURRENCY_CODE not in (104,156,978,392 ,458,702,764) and  authTXN_CURRENCY_CODE != authTXN_BILLING_CURRENCY_ID AND Card_Name ='Visa')  -- For VISA 
              THEN (AUTHTXN_REQUEST_AMT/ (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'VISA'))
              WHEN (authTXN_CURRENCY_CODE not in (104,156,978,392 ,458,702,764) and  authTXN_CURRENCY_CODE != authTXN_BILLING_CURRENCY_ID AND Card_Name LIKE '%JCB')   -- For JCB
              THEN (AUTHTXN_REQUEST_AMT/ (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'JCB'))
              WHEN (AUTHTXN_CURRENCY_CODE not in (104,156,978,392 ,458,702,764) and AUTHTXN_CURRENCY_CODE != AUTHTXN_BILLING_CURRENCY_ID AND Card_Name LIKE '%Master')
              THEN (AUTHTXN_REQUEST_AMT/ (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'MASTER'))
              WHEN (authTXN_CURRENCY_CODE not in (104,156,978,392 ,458,702,764) and  authTXN_CURRENCY_CODE != authTXN_BILLING_CURRENCY_ID)
              THEN (AUTHTXN_REQUEST_AMT/ (select rate from USD_rate where C_code = 840))
              ELSE AUTHTXN_REQUEST_AMT END  AS Trans_Amt,
       
         CASE WHEN authTXN_BILLING_CURRENCY_ID != 840 AND authTXN_BILLING_CURRENCY_ID = '104'  AND Card_Name LIKE '%JCB'
              THEN (AUTHTXN_REQUEST_AMT/ (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'JCB'))
              WHEN authTXN_BILLING_CURRENCY_ID != 840 AND authTXN_BILLING_CURRENCY_ID = '104'  AND Card_Name = 'Visa'
              THEN (AUTHTXN_REQUEST_AMT/ (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'VISA'))
              WHEN authTXN_BILLING_CURRENCY_ID != 840 AND authTXN_BILLING_CURRENCY_ID = '104'  AND Card_Name LIKE '%Master'
              THEN (AUTHTXN_REQUEST_AMT/ (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'MASTER'))
              WHEN authTXN_BILLING_CURRENCY_ID != 840 AND authTXN_BILLING_CURRENCY_ID in (104,156,978,392,458,702,764) 
              THEN (AUTHTXN_REQUEST_AMT/ (select rate from USD_rate where C_code = 840))
              ELSE AUTHTXN_REQUEST_AMT END  AS  Trans_Amt_USD,
       
         CASE WHEN authTXN_CURRENCY_CODE != '104' AND authTXN_CURRENCY_CODE = authTXN_BILLING_CURRENCY_ID AND Card_Name LIKE '%JCB'
              THEN (AUTHTXN_REQUEST_AMT * (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'JCB'))
              WHEN authTXN_CURRENCY_CODE != '104' AND authTXN_CURRENCY_CODE = authTXN_BILLING_CURRENCY_ID AND Card_Name = 'Visa'
              THEN (AUTHTXN_REQUEST_AMT *(select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'VISA'))
              WHEN authTXN_CURRENCY_CODE != '104' AND authTXN_CURRENCY_CODE = authTXN_BILLING_CURRENCY_ID AND Card_Name LIKE '%Master'
              THEN (AUTHTXN_REQUEST_AMT * (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'MASTER'))
              WHEN (authTXN_BILLING_CURRENCY_ID != 104 AND authTXN_CURRENCY_CODE = authTXN_BILLING_CURRENCY_ID) 
              THEN AUTHTXN_REQUEST_AMT*(select rate from USD_rate where C_code = authTXN_CURRENCY_CODE )
              ELSE AUTHTXN_REQUEST_AMT end AS Trans_Amt_MMK,    

         CASE WHEN Card_Name = 'Visa'    THEN (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'VISA') 
              WHEN Card_Name LIKE '%JCB' THEN (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'JCB' ) 
              WHEN Card_Name LIKE '%Master'  THEN (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'MASTER')
              ELSE (select rate from USD_rate where C_code = 840 ) END AS MMK_Rate,

 		 CASE WHEN authTXN_CURRENCY_CODE in (156,978,392,458,702,764) AND Card_Name LIKE '%JCB'
              THEN '1USD' +' = '+ trim(CONVERT(CHAR, (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'JCB' ) / (select rate from USD_rate where C_code = authTXN_CURRENCY_CODE)))  +' '+ CURRENCY_CODE
              WHEN authTXN_CURRENCY_CODE in (156,978,392,458,702,764) AND Card_Name = 'Visa'  
              THEN '1USD' +' = '+ trim(CONVERT(CHAR, (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'VISA' ) / (select rate from USD_rate where C_code = authTXN_CURRENCY_CODE))) +' '+ CURRENCY_CODE
              WHEN AUTHTXN_CURRENCY_CODE in (156,978,392,458,702,764) AND Card_Name LIKE '%Master'
              THEN '1USD' +' = '+ trim(CONVERT(CHAR, (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'MASTER') / (select rate from USD_rate where C_code = AUTHTXN_CURRENCY_CODE)))+' '+ CURRENCY_CODE 
              WHEN authTXN_CURRENCY_CODE in (156,978,392,458,702,764)  
              THEN '1USD' +' = '+ trim(CONVERT(CHAR, (select rate from USD_rate where C_code = 840 ) / (select rate from USD_rate where C_code = authTXN_CURRENCY_CODE)))+CURRENCY_CODE
              ELSE ' ' END as Remarks,
		      TRAN_TYPE,			  
  
  AUTHTXN_MERCHANT_ID, AUTHTXN_MERCHANT_NAME, TERMINAL_ID, MERCHANT_TRADE_NAME, MERCHANT_DBA_NAME, ADDRESS, CITY, STATE,

 'EDC_Acquiring_OCardZone' AS DATASOURCE

from openquery (mstocz,' 
WITH EDC_BATHCH_DATA AS (
            SELECT REQUEST_DATE AS TRN_DATE, TRANSACTION_ID,  CARD_NO, 
                 SUBSTR(REFERENCE_NUMBER,2,13) AS REFERENCE_NUMBER,
                 SUBSTR(MERCHANT_ID,2,15) AS MERCHANT_ID,
                 TERMINAL_ID, CHANNEL 
                 FROM ODI_ADW.CBM_MIS_EDC_ACQTRN
                 --WHERE REQUEST_DATE = TO_CHAR(SYSDATE-2,''YYYYMMDD'')
                 WHERE REQUEST_DATE = ''20250520''
            ) ,
ALL_CZ_DATA AS (
					SELECT DISTINCT * FROM (
						SELECT 
							OAUTHTXN_RETRIEVAL_REFNO AS AUTHTXN_RETRIEVAL_REFNO,
							OAUTHTXN_NO AS AUTHTXN_NO,
							OAUTHTXN_MCC_ID AS AUTHTXN_MCC_ID,
							OAUTHTXN_TXN_ENTRY_MODE AS AUTHTXN_TXN_ENTRY_MODE,
							OAUTHTXN_TXNTYPE_ID AS AUTHTXN_TXNTYPE_ID,
							OAUTHTXN_SOURCE AS AUTHTXN_SOURCE,
							OAUTHTXN_COUNTRY_CODE AS AUTHTXN_COUNTRY_CODE,
							OAUTHTXN_CARD_NO AS AUTHTXN_CARD_NO,
							OAUTHTXN_GEOGRAPHY_IND AS AUTHTXN_GEOGRAPHY_IND,
							OAUTHTXN_CRDBRAND_ID AS AUTHTXN_CRDBRAND_ID, 
							OAUTHTXN_CRDPLAN_ID AS AUTHTXN_CRDPLAN_ID,
							OAUTHTXN_CURRENCY_CODE AS AUTHTXN_CURRENCY_CODE,
							OAUTHTXN_DEST AS AUTHTXN_DEST,
							OAUTHTXN_CUST_ID AS AUTHTXN_CUST_ID,							
							OAUTHTXN_MERC_MDR_AMT AS AUTHTXN_MERC_MDR_AMT,

							OAUTHTXN_APPROVED_AMT AS AUTHTXN_APPROVED_AMT,
							OAUTHTXN_REQUEST_AMT AS AUTHTXN_REQUEST_AMT,
						
							OAUTHTXN_REQUEST_DATE AS AUTHTXN_REQUEST_DATE,
							OAUTHTXN_BILLING_CURRENCY_ID AS AUTHTXN_BILLING_CURRENCY_ID,
							TXNTYPE_BASE_TXNTYPE_ID,
							BILLCURR.CURRENCY_CODE,CARDTYPE.INFO_DESC,CRDBRAND_TYPE,CRDPLAN_PRODUCT_NAME,

							OAUTHTXN_MERCHANT_ID AS AUTHTXN_MERCHANT_ID,
							OAUTHTXN_MERCHANT_NAME AS AUTHTXN_MERCHANT_NAME, 
							OAUTHTXN_TERMINAL_ID AS AUTHTXN_TERMINAL_ID, 
							MERCHANT_TRADE_NAME, MERCHANT_DBA_NAME, 
							'''' ADDRESS , '''' CITY , '''' STATE 

						FROM ONECARD.CZ_OAUTHTXN 
						LEFT JOIN ONECARD.CZ_TXNTYPE ON OAUTHTXN_TXNTYPE_ID = TXNTYPE_ID AND OAUTHTXN_SOURCE = TXNTYPE_CHANNEL
						LEFT JOIN ONECARD.CZ_CRDBRAND ON OAUTHTXN_CRDBRAND_ID = CRDBRAND_ID
						LEFT JOIN ONECARD.CZ_CRDPLAN ON OAUTHTXN_CRDPLAN_ID = CRDPLAN_ID
						LEFT JOIN ONECARD.CZ_CRDCHGTYPE ON CRDPLAN_CHARGE_TYPE = CRDCHGTYPE_ID
						LEFT JOIN ONECARD.CZ_INFO CARDTYPE ON CRDCHGTYPE_CRDR_IND = CARDTYPE.INFO_CODE AND CARDTYPE.INFO_FIELD=''SETTLE_IND'' AND CARDTYPE.INFO_TABLE = ''GENERAL''
						LEFT JOIN ONECARD.CZ_CURRENCY BILLCURR ON OAUTHTXN_CURRENCY_CODE = BILLCURR.CURRENCY_ID
						LEFT JOIN ONECARD.CZ_CARD CARD ON CARD.CARD_NO = OAUTHTXN_CARD_NO
						LEFT JOIN ONECARD.CZ_MERCHANT ON MERCHANT_ID = OAUTHTXN_MERCHANT_ID
						-- LEFT JOIN ONECARD.CZ_ADDRESS ON ADDRESS_ID = CARD.CARD_CUST_ID AND ADDRESS_TYPE_ID = ''MAIN''  --* Acquring Customer info will not keep in our DB
						-- WHERE TO_CHAR(TO_DATE(OAUTHTXN_REQUEST_DATE, ''yyyymmdd''),''YYYYMMDD'') = TO_CHAR(SYSDATE-1,''YYYYMMDD'')
						WHERE OAUTHTXN_REQUEST_DATE =''20250520''
						AND (TXNTYPE_REV_VOID_IND IS NULL OR (TXNTYPE_REV_VOID_IND != ''R'' AND TXNTYPE_REV_VOID_IND != ''V''))
						AND OAUTHTXN_RESPONSE_CODE=''00''
						AND OAUTHTXN_MCC_ID != ''6011''
						AND OAUTHTXN_CUST_ID IS  NULL
						and OAUTHTXN_SOURCE != ''MPI'' 
					  )	
					)			
 
 SELECT DISTINCT * FROM (
 SELECT AUTHTXN_RETRIEVAL_REFNO,

	   CASE WHEN M.CARD_NO LIKE (''9%'') THEN ''MPU''
            WHEN M.CARD_NO LIKE (''6%'') THEN ''UPI''
            WHEN M.CARD_NO LIKE (''3%'') THEN ''JCB''
            WHEN M.CARD_NO LIKE (''4%'') THEN ''Visa''
            WHEN M.CARD_NO LIKE (''5%'') OR M.CARD_NO LIKE (''2%'')  THEN ''Master'' --END AS CARD_NAME,
			WHEN CRDPLAN_PRODUCT_NAME LIKE ''%VISA%'' or CRDPLAN_PRODUCT_NAME LIKE ''%VSI%'' THEN ''Visa''   ---/ cardName is not cover from batch file because of this(PREAUTH & SALECOMADV) so cardName is null and use CRDPLAN_PRODUCT_NAME to fix it
			WHEN CRDPLAN_PRODUCT_NAME LIKE ''%MASTER%'' THEN ''Master''   
			WHEN CRDPLAN_PRODUCT_NAME LIKE ''%JCB%'' OR CRDPLAN_PRODUCT_NAME LIKE ''%MJC%'' THEN ''JCB''  
			WHEN CRDPLAN_PRODUCT_NAME LIKE ''%CUP%'' or CRDPLAN_PRODUCT_NAME LIKE ''%UPI%'' THEN ''UPI''  
			WHEN (CRDPLAN_PRODUCT_NAME LIKE ''%MPU%'' OR CRDPLAN_PRODUCT_NAME LIKE ''%MPS%'') 
			AND CRDPLAN_PRODUCT_NAME NOT LIKE ''%MPU/%'' THEN ''MPU'' END AS CARD_NAME,
			 
       CRDPLAN_PRODUCT_NAME,CRDBRAND_TYPE,INFO_DESC,CURRENCY_CODE,        
       CASE WHEN CURRENCY_CODE NOT IN (''MMK'',''USD'',''EUR'',''SGD'',''THB'',''CNY'',''MYR'',''JPY'') THEN ''USD''
             WHEN CURRENCY_CODE IS NULL THEN ''USD''
             ELSE CURRENCY_CODE END AS CURRENCY, 

			CASE WHEN AUTHTXN_MCC_ID= ''6011''  THEN ''ATM''
                 WHEN AUTHTXN_TXN_ENTRY_MODE IN (''CHIP_READ'',''CONTACTLESS_CHIP'',''MAGSTRIPE_READ'')  THEN ''POS''
                 WHEN AUTHTXN_TXN_ENTRY_MODE = ''MANUAL_ENTRY'' AND AUTHTXN_TXNTYPE_ID = ''SALECOMADV'' THEN ''POS''
				 WHEN AUTHTXN_SOURCE = ''EDC'' THEN ''POS''
                 WHEN AUTHTXN_TXN_ENTRY_MODE IS NULL OR  AUTHTXN_TXN_ENTRY_MODE  
                      IN ( ''ECOMMERCE'', ''ECOMMERCE_3D'', ''ECOMMERCE_ATTEMP'', ''ECOMMERCE_RECURR'', 
						   ''EGAMBLING'', ''FALL_BACK'', ''DEFAULT'', ''MANUAL_ENTRY'', ''MOTO'' , ''RECURRING'',''UNKNOWN'', ''ECOMMERCE_VBV'', 
					  	   ''ECOMMERCE_SC'',''RECURRING'',''MOTO'' ,''UNKNOWN'',''MANUAL_ENTRY'') AND AUTHTXN_TXNTYPE_ID != ''SALECOMADV'' THEN ''E-Commerce''
				WHEN AUTHTXN_SOURCE = ''MPI'' THEN ''E-Commerce'' ELSE ''None'' END AS SOURCE,	
      CASE WHEN (AUTHTXN_CUST_ID IS NOT NULL AND AUTHTXN_TERMINAL_ID IN (SELECT TERMINAL_ID FROM ONECARD.CZ_TERMINAL)) THEN ''ONUS'' 
         WHEN AUTHTXN_MERCHANT_ID LIKE ''AYA%'' THEN ''ONUS''---KO TINT
         ELSE AUTHTXN_MERCHANT_ID END AS TRAN_CATEGORY,				

                CASE WHEN TXNTYPE_BASE_TXNTYPE_ID IN (''PAYMENT'',''TOPUP'') THEN 0 ELSE 1 END AS TRANS_COUNT,   
				CASE WHEN AUTHTXN_TXNTYPE_ID IN (''REFUND'',''REFUND_PRE'',''REFUND_PRV'',''REFUND1'',''REFUNDADV'',''RFNDNOAUTH'') THEN 1 ELSE 0 END AS TRAN_TYPE,
			   
				   TO_CHAR(TO_DATE(AUTHTXN_REQUEST_DATE, ''yyyymmdd''),''YYYYMMDD'') AS TRAN_DATE,
				   --M.TRN_DATE AS TRAN_DATE,
				   AUTHTXN_MCC_ID,
				   AUTHTXN_TXN_ENTRY_MODE,
				   TXNTYPE_BASE_TXNTYPE_ID,
				   AUTHTXN_COUNTRY_CODE,
				   AUTHTXN_CARD_NO,
				   M.CARD_NO AS CARD_NO,
				   AUTHTXN_CURRENCY_CODE,
				   AUTHTXN_BILLING_CURRENCY_ID,
				   
				   AUTHTXN_TXNTYPE_ID,
				   AUTHTXN_APPROVED_AMT,   
				   AUTHTXN_REQUEST_AMT,

				   AUTHTXN_MERC_MDR_AMT,
				   AUTHTXN_CUST_ID,
				   1 AS USD_RATE,
							
				 AUTHTXN_DEST,
				 AUTHTXN_SOURCE,
				 AUTHTXN_GEOGRAPHY_IND,
				
				 AUTHTXN_MERCHANT_ID,
				 AUTHTXN_MERCHANT_NAME, 
				 AUTHTXN_TERMINAL_ID AS TERMINAL_ID, 
				 MERCHANT_TRADE_NAME, MERCHANT_DBA_NAME, 
				 ADDRESS, CITY, STATE

			FROM ALL_CZ_DATA 
            LEFT JOIN EDC_BATHCH_DATA M ON M.REFERENCE_NUMBER = AUTHTXN_RETRIEVAL_REFNO AND M.TRANSACTION_ID = AUTHTXN_NO
            WHERE AUTHTXN_REQUEST_DATE =''20250520'' 
			--WHERE TO_CHAR(TO_DATE(AUTHTXN_REQUEST_DATE, ''yyyymmdd''),''YYYYMMDD'') = TO_CHAR(SYSDATE-1,''YYYYMMDD'')
		) ALL_INFO WHERE SOURCE = ''POS'' 
')TBL LEFT JOIN CardIssuer ON CardIssuer.BIN =  SUBSTRING(CARD_NO,1,6) 
      WHERE AUTHTXN_TXNTYPE_ID NOT IN (SELECT TXNTYPE_ID FROM CZ_TRAN_TYPE) --GET CZ_TYPE UPDATE FILE FROM Ma Shwe Sin

------------------------------------------------------------------------ END CardZone ------------------------------------------------------------------
UNION ALL

------------------------------------------------------------------------- START CR2 --------------------------------------------------------------------


SELECT  REF_NO,
        CASE WHEN CARD_NAME + CATEGORY_OF_CARD = 'JCBCo-brand' THEN 'MPU-JCB' 
         WHEN CARD_NAME + CATEGORY_OF_CARD = 'UPICo-brand' THEN 'MPU-UPI' ELSE CARD_NAME END AS CARD_NAME, 
		 CARD_NO,

    CASE WHEN SUBSTRING(USED_CARD_QUANTITY,1,4)='3571' THEN 'Debit' 
         WHEN SUBSTRING(USED_CARD_QUANTITY,1,4)='3565' THEN 'Credit' 
		 WHEN SUBSTRING(USED_CARD_QUANTITY,1,4)='6234' THEN 'Debit'
		 WHEN SUBSTRING(USED_CARD_QUANTITY,1,4)='6244' THEN 'Credit' 
		 WHEN SUBSTRING(USED_CARD_QUANTITY,1,6) NOT IN (SELECT BIN FROM PSSD_INTERCHANGE) THEN 'Credit' ELSE CATEGORY_OF_CARD END AS CATEGORY_OF_CARD,

    CURRENCY, USED_CARD_QUANTITY, SOURCE, USED_LOCATION, TRANS_COUNT,
    TRANS_AMT,
  
       CASE WHEN CARD_NAME = 'Visa'   THEN (Trans_Amt_USD/(select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'VISA'))
            WHEN CARD_NAME LIKE '%JCB'    THEN (Trans_Amt_USD/(select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'JCB'))
            WHEN CARD_NAME LIKE '%Master' THEN (Trans_Amt_USD/(select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'MASTER'))
            ELSE ROUND((Trans_Amt_USD/(select rate from USD_rate where C_code =840)),2) END as TRANS_AMT_USD,

         TRANS_AMT_MMK, 
        
       CASE WHEN CARD_NAME = 'Visa' THEN (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'VISA')
            WHEN CARD_NAME LIKE '%JCB%'  THEN (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'JCB')
            WHEN CARD_NAME LIKE '%Master'  THEN (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'MASTER')
            ELSE (select rate from USD_rate where  C_code =840) END AS MMK_RATE,

 		REMARKS, TRAN_TYPE,			

         AUTHTXN_MERCHANT_ID, AUTHTXN_MERCHANT_NAME, TERMINAL_ID, MERCHANT_TRADE_NAME, MERCHANT_DBA_NAME, ADDRESS, CITY, STATE,
		
		'CR2' AS DATASOURCE
        
FROM OPENQUERY(MSTOCR2 , '  

SELECT  P37_RRN AS REF_NO, 
        CASE WHEN SUBSTR(M.P02_PAN,0,1)=9  THEN ''MPU''
             WHEN SUBSTR(M.P02_PAN,0,1)=3 THEN ''JCB''
             WHEN SUBSTR(M.P02_PAN,0,1)=4 THEN ''Visa''
             WHEN SUBSTR(M.P02_PAN,0,1)=6 THEN ''UPI'' 
             ELSE ''Master'' END AS CARD_NAME,
		SUBSTR(M.P02_PAN,1,6) as CARD_NO,
        CASE WHEN SUBSTR(M.P02_PAN,0,1)=6 OR SUBSTR(M.P02_PAN,0,1)=3 THEN ''Co-brand'' 
         WHEN SUBSTR(P02_PAN,0,6)=''460287'' THEN ''Pre-paid''
         WHEN SUBSTR(M.P02_PAN,0,1)=4 THEN ''Credit'' ELSE ''Debit'' END AS CATEGORY_OF_CARD,   

       ''MMK'' AS CURRENCY, TO_CHAR(P02_PAN) AS USED_CARD_QUANTITY,

        CASE WHEN (SUBSTR(P41_CRD_AC_TRM_ID,5,4) IN (SELECT ID FROM BWS_ATM_NETWORK) AND 
                  SUBSTR(P02_PAN,0,16) IN (SELECT DISTINCT CARD_NUM FROM CMS_CARD_)) THEN ''ONUS'' 
                  ELSE SUBSTR(P41_CRD_AC_TRM_ID,0,18) END AS TID,

          ''ATM'' AS SOURCE, 
          ''Local'' AS USED_LOCATION, 
          1 AS TRANS_COUNT,        
        
        CASE WHEN SUBSTR(D.TXN_CODE,1,3) LIKE (''0%'') OR SUBSTR(D.TXN_CODE,1,3) LIKE (''7%'') THEN CONCAT(''-'',(M.P04_AMT_TXN - nvl(substr(M.P28_AMT_TXN_FEE,2,10),0)))/100
             WHEN SUBSTR(D.TXN_CODE,1,3) LIKE (''0%'') OR SUBSTR(D.TXN_CODE,1,3) LIKE (''7%'') and M.P28_AMT_TXN_FEE IS NULL THEN M.P04_AMT_TXN
             ELSE ((M.P04_AMT_TXN)- substr(M.P28_AMT_TXN_FEE,2,10))/100 END AS TRANS_AMT, --D.TXN_CODE as TXN_CODE,
       
        CASE WHEN SUBSTR(D.TXN_CODE,1,3) LIKE (''0%'') OR SUBSTR(D.TXN_CODE,1,3) LIKE (''7%'') THEN CONCAT(''-'',(TRUNC(M.P04_AMT_TXN) - nvl(substr(M.P28_AMT_TXN_FEE,2,10),0)))/100
             WHEN SUBSTR(D.TXN_CODE,1,3) LIKE (''0%'') OR SUBSTR(D.TXN_CODE,1,3) LIKE (''7%'') and M.P28_AMT_TXN_FEE IS NULL THEN (TRUNC((M.P04_AMT_TXN/100),2))
             ELSE (TRUNC((M.P04_AMT_TXN/100),2)) - (SUBSTR(M.P28_AMT_TXN_FEE,2,8)/100) END AS TRANS_AMT_USD,

        CASE WHEN SUBSTR(D.TXN_CODE,1,3) LIKE (''0%'') OR SUBSTR(D.TXN_CODE,1,3) LIKE (''7%'') THEN CONCAT(''-'',(M.P04_AMT_TXN - nvl(substr(M.P28_AMT_TXN_FEE,2,10),0)))/100
             WHEN SUBSTR(D.TXN_CODE,1,3) LIKE (''0%'') OR SUBSTR(D.TXN_CODE,1,3) LIKE (''7%'') and M.P28_AMT_TXN_FEE IS NULL THEN M.P04_AMT_TXN
             ELSE ((M.P04_AMT_TXN)- substr(M.P28_AMT_TXN_FEE,2,10))/100 END AS Trans_Amt_MMK,       
 
        1 AS USDRATE, '' '' AS REMARKS ,  0 AS TRAN_TYPE,P37_RRN,
             
        '''' AUTHTXN_MERCHANT_ID, '''' AUTHTXN_MERCHANT_NAME, P41_CRD_AC_TRM_ID AS TERMINAL_ID, 
        '''' MERCHANT_TRADE_NAME, '''' MERCHANT_DBA_NAME, 
        P43_CRD_AC_NAMELOC AS ADDRESS, CITYSTATE AS CITY, CITYSTATE AS STATE

FROM SAR_ISO_MSG_ M
LEFT JOIN BANKWORLD.GTW_RPT_TXN_DESCRIPTION D ON M.P61_RESERVED_PRV = D.RAW_FUN_CODE
LEFT JOIN BANKWORLD.BWS_BRANCHES_ BRANCH ON BRANCH.BRANCH = SUBSTR(P41_CRD_AC_TRM_ID,1,4)
WHERE SUBSTR(TIMESTAMP, 1,8) =''20250520'' --TO_CHAR(SYSDATE, ''YYYYMMDD'')-1
        AND P39_RSP_CODE=''00'' 
        AND P18_MTYPE=''6011''
        AND (P03_PCODE LIKE ''01%'' OR  P03_PCODE LIKE ''40%'')
        AND M.P04_AMT_TXN <>0 
        AND P02_PAN NOT IN (SELECT CARD_NUM FROM BANKWORLD.CMS_CARD)
        AND SUBSTR(P02_PAN,1,6) NOT LIKE (''999%'')

UNION ALL

SELECT  P37_RRN AS REF_NO,

        CASE WHEN SUBSTR(M.P02_PAN,0,1)=9  THEN ''MPU''
             WHEN SUBSTR(M.P02_PAN,0,1)=3 THEN ''JCB''
             WHEN SUBSTR(M.P02_PAN,0,1)=4 THEN ''Visa''
             WHEN SUBSTR(M.P02_PAN,0,1)=6 THEN ''UPI'' 
             ELSE ''Master'' END AS CARD_NAME,
		SUBSTR(M.P02_PAN,1,6) as CARD_NO,
        CASE WHEN SUBSTR(M.P02_PAN,0,1)=6 OR SUBSTR(M.P02_PAN,0,1)=3 THEN ''Co-brand'' 
             WHEN SUBSTR(P02_PAN,0,6)= 950310 THEN ''Debit''
             WHEN SUBSTR(M.P02_PAN,0,1)=4 THEN ''Credit'' 
             WHEN SUBSTR(P02_PAN,0,6)=''460287'' THEN ''Pre-paid''
             ELSE ''Credit'' END AS CATEGORY_OF_CARD,   

     ''MMK'' AS CURRENCY,
       TO_CHAR(P02_PAN) AS USED_CARD_QUANTITY,

        CASE WHEN (SUBSTR(P41_CRD_AC_TRM_ID,5,4) IN (SELECT ID FROM BWS_ATM_NETWORK) AND 
             SUBSTR(P02_PAN,0,16) IN (SELECT DISTINCT CARD_NUM FROM CMS_CARD_)) THEN ''ONUS'' 
             ELSE SUBSTR(P41_CRD_AC_TRM_ID,0,18) END AS TID,

            ''ATM'' AS SOURCE, ''Local'' AS USED_LOCATION, 1 AS TRANS_COUNT,

        CASE WHEN SUBSTR(D.TXN_CODE,1,3) LIKE (''0%'') OR SUBSTR(D.TXN_CODE,1,3) LIKE (''7%'') THEN CONCAT(''-'',(M.P04_AMT_TXN - nvl(substr(M.P28_AMT_TXN_FEE,2,10),0)))/100
             WHEN SUBSTR(D.TXN_CODE,1,3) LIKE (''0%'') OR SUBSTR(D.TXN_CODE,1,3) LIKE (''7%'') and M.P28_AMT_TXN_FEE IS NULL THEN M.P04_AMT_TXN
             ELSE ((M.P04_AMT_TXN)- substr(M.P28_AMT_TXN_FEE,2,10))/100 END AS TRANS_AMT, 
    
        CASE WHEN SUBSTR(D.TXN_CODE,1,3) LIKE (''0%'') OR SUBSTR(D.TXN_CODE,1,3) LIKE (''7%'') THEN CONCAT(''-'',(TRUNC(M.P04_AMT_TXN) - nvl(substr(M.P28_AMT_TXN_FEE,2,10),0)))/100
             WHEN SUBSTR(D.TXN_CODE,1,3) LIKE (''0%'') OR SUBSTR(D.TXN_CODE,1,3) LIKE (''7%'') and M.P28_AMT_TXN_FEE IS NULL THEN (TRUNC((M.P04_AMT_TXN/100),2))
             ELSE (TRUNC((M.P04_AMT_TXN/100),2)) - (SUBSTR(M.P28_AMT_TXN_FEE,2,8)/100) END AS TRANS_AMT_USD,

        CASE WHEN SUBSTR(D.TXN_CODE,1,3) LIKE (''0%'') OR SUBSTR(D.TXN_CODE,1,3) LIKE (''7%'') THEN CONCAT(''-'',(M.P04_AMT_TXN - nvl(substr(M.P28_AMT_TXN_FEE,2,10),0)))/100
             WHEN SUBSTR(D.TXN_CODE,1,3) LIKE (''0%'') OR SUBSTR(D.TXN_CODE,1,3) LIKE (''7%'') and M.P28_AMT_TXN_FEE IS NULL THEN M.P04_AMT_TXN
             ELSE ((M.P04_AMT_TXN)- substr(M.P28_AMT_TXN_FEE,2,10))/100 END AS Trans_Amt_MMK,
        
    1 AS USDRATE,'' '' AS REMARKS, 0 AS TRAN_TYPE, P37_RRN,
    
    '''' AUTHTXN_MERCHANT_ID, '''' AUTHTXN_MERCHANT_NAME, P41_CRD_AC_TRM_ID AS TERMINAL_ID, 
    '''' MERCHANT_TRADE_NAME, '''' MERCHANT_DBA_NAME, 
    P43_CRD_AC_NAMELOC AS ADDRESS, CITYSTATE AS CITY, CITYSTATE AS STATE
        
FROM SAR_ISO_MSG_ARCHIVE_ M
LEFT JOIN BANKWORLD.GTW_RPT_TXN_DESCRIPTION D ON M.P61_RESERVED_PRV = D.RAW_FUN_CODE
LEFT JOIN BANKWORLD.BWS_BRANCHES_ BRANCH ON BRANCH.BRANCH = SUBSTR(P41_CRD_AC_TRM_ID,1,4)
WHERE SUBSTR(TIMESTAMP, 1,8) =''20250520'' --TO_CHAR(SYSDATE, ''YYYYMMDD'')-1
        AND P39_RSP_CODE=''00'' 
        AND P18_MTYPE=''6011''
        AND (P03_PCODE LIKE ''01%'' OR  P03_PCODE LIKE ''40%'')
        AND M.P04_AMT_TXN <>0 
        AND P02_PAN NOT IN (SELECT CARD_NUM FROM BANKWORLD.CMS_CARD)
        AND SUBSTR(P02_PAN,1,6) NOT LIKE (''999%'') 

')TBL LEFT JOIN Cardissuer ON Cardissuer.BIN = CARD_NO WHERE CARD_NO NOT IN (SELECT BIN FROM PSSD_Interchange)
--- END >>  CR2 : ATM 


--------------------------------------------------------------------- END CR2 --------------------------------------------------------------------

UNION ALL

---------------------------------------------------------------------- START PPAY ------------------------------------------------------------------

SELECT  
		RETRIEVALREFERENCENUMBER AS REF_NO,
	 	CASE WHEN ppay.cardType='MasterCard' AND SUBSTRING([cardNumber],1,6) IN ('519430','515169') THEN 'MPU-Master' 
			 WHEN ppay.cardType='MasterCard' THEN 'Master' 
	    ELSE ppay.cardType END AS CARD_NAME,
   		SUBSTRING([cardNumber],1,6) as CARD_NO,
         --'Credit' AS CATEGORY_OF_CARD,
		CASE WHEN SUBSTRING([cardNumber],1,6) IN (SELECT BIN FROM CardIssuer) AND  CardIssuer.CardType =  'DEBIT'   THEN 'Debit'
			 WHEN SUBSTRING([cardNumber],1,6) IN (SELECT BIN FROM CardIssuer) AND  CardIssuer.CardType =  'CREDIT'  THEN 'Credit'
			 WHEN SUBSTRING([cardNumber],1,6) IN (SELECT BIN FROM CardIssuer) AND  CardIssuer.CardType =  'PREPAID' THEN 'Prepaid'
		ELSE 'Credit' END AS Category_of_Card,
        MERCHANTCURRENCY AS CURRENCY,    
        CARDNUMBER AS USED_CARD_QUANTITY,

		CASE WHEN MERCHANTNAME='AYA ATM' THEN 'ATM' ELSE 'POS' END AS SOURCE,
		CASE WHEN [FOREIGN]='FALSE' THEN 'Local' ELSE 'Oversea' END AS USED_LOCATION,
      
		1 AS TRANS_COUNT,		
		MERCHANTAMOUNTSIGNED AS TRANS_AMT,  
  
		CASE WHEN merchantCurrency='MMK' AND ppay.cardType = 'Visa'
				THEN (merchantAmountSigned/(SELECT RATE FROM CBM_Exchange_Rate WHERE CurrencyCode = 840 AND CardBrand = 'VISA'))
			 WHEN merchantCurrency='MMK' AND ppay.cardType = 'MasterCard'
				THEN (merchantAmountSigned/(SELECT RATE FROM CBM_Exchange_Rate WHERE CurrencyCode = 840 AND CardBrand = 'MASTER'))
			 WHEN merchantCurrency='USD' 
				THEN merchantAmountSigned END AS Trans_Amt_USD,
  
		CASE WHEN merchantCurrency='USD' AND ppay.cardType = 'Visa'
				THEN (merchantAmountSigned*(select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'VISA'))
			 WHEN merchantCurrency='USD' AND ppay.cardType = 'MasterCard'
				THEN (merchantAmountSigned*(select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'MASTER')) 
			 WHEN merchantCurrency='MMK' 
			THEN merchantAmountSigned END AS Trans_Amt_MMK,


       --CASE WHEN ppay.cardType = 'Visa'  THEN (SELECT RATE FROM CBM_EXCHANGE_RATE WHERE CURRENCYCODE = 840 AND CARDBRAND = 'VISA')
       --     ELSE (SELECT RATE FROM USD_RATE WHERE  C_CODE =840) END AS MMK_RATE,

       CASE WHEN ppay.cardType = 'Visa'    THEN (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'VISA') 
            WHEN ppay.cardType = 'JCB'     THEN (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'JCB' ) 
            WHEN ppay.cardType = 'MasterCard'  THEN (select RATE from CBM_Exchange_Rate where CurrencyCode = 840 AND CardBrand = 'MASTER')
            ELSE (SELECT RATE FROM USD_RATE WHERE C_CODE =840) END AS MMK_RATE, 

    ' ' AS REMARKs,--'' as  mod_date,
         0 AS TRAN_TYPE,
		 mid  AUTHTXN_MERCHANT_ID, 
		  description as AUTHTXN_MERCHANT_NAME,
		  terminalId as TERMINAL_ID, 
		  '' MERCHANT_TRADE_NAME, 
		  merchantDbaName as MERCHANT_DBA_NAME, 
		  '' ADDRESS, merchantDbaCity as CITY,  merchantDbaState as STATE, 
		 'PPAY' AS DATASOURCE
  
FROM PPAY
LEFT JOIN Cardissuer ON Cardissuer.BIN = SUBSTRING([cardNumber],1,6)
WHERE CONVERT(nvarchar, submittedDate, 112) ='20250520' 
--WHERE CONVERT(nvarchar, submittedDate, 112) = CONVERT(nvarchar, GETDATE(), 112)-1
AND replace(SUBSTRING([cardNumber],1,6),'X',0) not in (select bin from PSSD_Interchange)

----------------------------------------------------------------------- END PPAY --------------------------------------------------------------------
) RAW 
------------------------------------------------------------------------END RAW ---------------------------------------------------------------------
--)TBL
--group by  SOURCE, CURRENCY, Remarks 
